#!/bin/bash

# This command is run directly, we exports some data and use the generate wrapper to finish settings things up
export SNAP=$(dirname $(readlink -f $0))
export SNAP_DATA=/var/lib$SNAP

exec "$SNAP/command-record-terminal.wrapper" $*
