name: terminal-recorder-demo
version: 0.42
summary: Record your terminal to replay them later!
description: This demo intend to show how to assemble different pieces, some coming from ubuntu, other coming from
 a git repo to create an amazing user experience by recording your terminal input and outputs and provide a webserver
 to replay those.
 This one is part of the demo tour at https://developer.ubuntu.com/snappy/get-started/as-dev

apps:
  asciinema-service:
    command: bin/asciinema-local-server
    daemon: simple
    plugs: [listener]
  record-terminal:
    command: record-terminal
    plugs: [unconfined-plug]

plugs:
  listener:
    interface: old-security
    caps: [network-listener]
  unconfined-plug:
    interface: old-security
    security-template: unconfined

parts:
  webserver:
    plugin: nodejs
    source: https://github.com/didrocks/asciinema-local-server.git
  asciinema:
    plugin: go
    source: https://github.com/asciinema/asciinema.git
  recorder-command-glue:
    plugin: copy
    source: https://github.com/didrocks/terminal-recorder-glue.git
    files:
      'record-terminal*': '.'
    stage-packages: [qrencode, byobu]
