name: sdc-demo
version: 0.42
summary: Demo for SDC
vendor: didrocks@ubuntu.com
description: Transform your home routeur in an intelligent machine
icon: icon.png

services:
  homedemo:
    start: bin/homedemo.exports -vv
    security-template: unconfined
  spheroSpeech:
    start: spheroSpeech
    security-template: unconfined

parts:
  demo:
    plugin: copy
    files:
      'bin/*': 'bin/'
      'home.map': 'home.map'
      'sphero.hw': 'sphero.hw'
      'logic.xml': 'logic.xml'
      'homedemo': 'homedemo'
    stage-packages:
     - python-dev
     - python-opencv
     - python-numpy
     - python-mock
     - python-yaml
  sensory:
    plugin: make
    source: https://github.com/didrocks/sensory-ubuntu-core-home-demo
    source-type: git
build-packages: [libasound2-dev]
